var shortForms = {
  "Anaheim": "ANA",
  "Arizona": "ARI",
  "Boston": "BOS",
  "Buffalo": "BUF",
  "Calgary": "CGY",
  "Carolina": "CAR",
  "Chicago": "CHI",
  "Colorado": "COL",
  "Columbus": "CBJ",
  "Dallas": "DAL",
  "Detroit": "DET",
  "Edmonton": "EDM",
  "Florida": "FLA",
  "Los Angeles": "LA",
  "Minnesota": "MIN",
  "Montreal": "MON",
  "Montr&#xE9;al": "MON",
  "Nashville": "NSH",
  "New Jersey": "NJ",
  "NY Islanders": "NYI",
  "NY Rangers": "NYR",
  "Ottawa": "OTT",
  "Philadelphia": "PHI",
  "Pittsburgh": "PIT",
  "San Jose": "SJ",
  "St Louis": "STL",
  "St. Louis": "STL",
  "Tampa Bay": "TB",
  "Toronto": "TOR",
  "Vancouver": "VAN",
  "Washington": "WSH",
  "Winnipeg": "WPG"
};

module.exports = shortForms;